wip: making a project base
PostScripton/accrual-loyalty-system-gophermart pull request #1
Opened 2022-10-11 21:36 UTC by PostScripton

2022-10-17 18:09 UTC, kilchik requested changes

2022-10-17 18:09 UTC, kilchik commented on internal/services/user.go
> +		return nil, err
Всегда обрамляй ошибки (например, с помощью errors.Wrap)

2022-10-17 18:09 UTC, kilchik commented on internal/repository/postgres/user.go
> +	if _, err := ur.db.Exec(ctx, sql, login, hashedPassword, now, now); err != nil {
При создании таблицы users можно выставить значение по-умолчанию для created_at и updated_at с помощью DEFAULT, тогда в запросе останется только меньше атрибутов для вставки

2022-10-17 18:09 UTC, kilchik commented on internal/repository/postgres/postgres.go
> +		<-ctx.Done()
Стоит продумать graceful shutdown, пч сейчас ctx никто явно не завершает, а стало быть при завершении работы сервиса функция pool.Close() вызвана не будет. Предлагаю этот момент оставить на финальную часть работы, а для вдохновения обратиться к статье https://www.rudderstack.com/blog/implementing-graceful-shutdown-in-go/

2022-10-17 18:09 UTC, kilchik commented on internal/repository/postgres/user.go
> +	if err := row.Scan(&user.ID, &user.Login, &user.Password, &user.CreatedAt, &user.UpdatedAt); err != nil {
Сейчас модель User одна и для БД и для контроллера, можно оставить так, но с точки зрения дальнейшего развития программы будет удобней сделать разные структуры User в postgres/models.go и models.go где-то на уровне контроллера. Этот момент хорошо описал Тимофей здесь https://practicum-students.slack.com/archives/C03U68G13B3/p1666006382300899

2022-10-17 18:09 UTC, kilchik commented on internal/services/auth.go
> +package services
Я бы предложил еще немного подумать о структуре пакетов. Сейчас services хранит в себе несколько сущностей, которые логически связаны, но само название services как будто подразумевает, что в него будут добавляться и другие сущности, не связанные с users. Я бы предложил выделить сущность (пакет/структуру) auther/Auther и наполнить ее кодом из services - как будто бы сейчас все из пакета services можно семантически вынести в такого рода сущность

2022-10-19 20:04 UTC, PostScripton commented on internal/services/user.go
> +		return nil, err
Не очень понял для чего именно тут это делать, но спасибо за совет!

2022-10-22 12:05 UTC, merged

2022-10-24 16:54 UTC, PostScripton commented on internal/repository/postgres/user.go
> +	if err := row.Scan(&user.ID, &user.Login, &user.Password, &user.CreatedAt, &user.UpdatedAt); err != nil {
Оставил модели для БД, а для запросов и ответов сделал свои структуры, таким образом они не пересекаются

2022-10-31 21:43 UTC, kilchik commented on internal/services/user.go
> +		return nil, err
В этой функции в трех местах возвращается err. Сможешь ли ты по ошибке однозначно идентифицировать, откуда она была возвращена? Из FindByLogin или Create? Идиоматичной является такая запись `пытаюсь сделать A: произошла такая-то ошибка`. Если у тебя произошла ошибка в функции C , которая вызывается в функции B, которая вызывается в функции A, то с такой нотацией получится однозначно определить последовательность действий и локализовать ошибку, если ее текст будет `пытаюсь сделать A: пытаюсь сделать B: пытаюсь сделать C: произошла ошибка`